#!/bin/sh

XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

# Wait for pipewire socket to be available
while [ ! -S "$XDG_RUNTIME_DIR/pipewire-0" ]; do
  sleep 0.5
done

exec /usr/bin/pipewire-pulse
