#!/bin/bash

DISTRO=$1

if [ -z "$DISTRO" ]; then
  echo "Please provide either 'fedora' or 'void'"
  exit 1
fi

cd ~/.dotfiles

if [ ! -d "$DISTRO" ]; then
    echo "Directory '$DISTRO' does not exist in .dotfiles."
    exit 1
fi

# Properly symlink files from the `shared` directory.
find shared -type f -not -name ".zshrc.shared" -not -path "*/scripts/*" | while read file; do
  target="$HOME${file#shared}"
  target_dir=$(dirname "target")

  if [ -d "$target" ]; then
    mkdir -p "$target"
  fi

  ln -sf "$HOME/.dotfiles/$file" "$target"
done

# Properly symlink files from specified distro directory.
find "$DISTRO" -type f -not -path "*/scripts/*" | while read file; do
  target="$HOME/${file#$DISTRO}"
  target_dir=$(dirname "target")

  if [ -d "$target" ]; then
    mkdir -p "$target"
  fi

  ln -sf "$HOME/.dotfiles/$file" "$target"
done

echo "Dotfiles successfully symlinked"
