#!/bin/bash

BATTERY=$(acpi -b | grep -oE '[0-9]+%')

echo "󰁹 $BATTERY"
# Only print the battery number if the command output starts with a number.
# On desktop, it won't start with a number as acpi is unable to find the
# battery for a power supply.
# if [[ $BATTERY =~ ^[0-9]+$ ]]; then
#   echo "󰁹 $BAT"
# fi

exit 0
