#!/bin/bash

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}" # Default to `$HOME/dotfiles` in case of improperly set environment variable.

link() {
  local src="$1"
  local dest="$2"
  local dest_dir=$(dirname "$dest")

  if [ ! -d "$dest_dir" ]; then
    mkdir -p "$dest_dir"
  fi

  # Ensure that, if the destination exists, that it is not a symlink.
  if [ -e "$dest" ] && [ ! -L "$dest" ]; then
    echo "  WARNING: $dest exists and is not a symlink, exiting"
    return
  fi

  ln -sf "$src" "$dest"
  echo "  $src -> $dest"
}

echo "Linking top-level dotfiles..."
find "$DOTFILES_DIR" -maxdepth 1 -type f -name ".*" | while read -r src; do
  file=$(basename "$src")
  link "$src" "$HOME/$file"
done

echo "Linking .config..."
find "$DOTFILES_DIR/.config" -type f | while read -r src; do
  relative="${src#"$DOTFILES_DIR/"}"
  link "$src" "$HOME/$relative"
done

echo "Linking scripts to ~/.local/bin..."
mkdir -p "$HOME/.local/bin"
find "$DOTFILES_DIR/scripts" -type f | while read -r src; do
  file=$(basename "$src")
  link "$src" "$HOME/.local/bin/$file"
done 

echo ""
echo "All dotfiles successfully symlinked!"

exit 0
