#!/bin/bash

find $DOTFILES_DIR/.config -type f | cut -d"/" -f 5- | while read file;
do
  target="$HOME/$file"
  target_dir=$(dirname "$target")

  if [ ! -d "$target_dir" ]; then
    mkdir -p "$target_dir"
  fi

  ln -sf "$DOTFILES_DIR/$file" "$target"
done
echo "Dotfiles successfully symlinked!"

find $DOTFILES_DIR/scripts -type f | while read script_path;
do
  file=$(basename "$script_path")
  target="$HOME/.local/bin/$file"

  ln -sf "$script_path" "$target"
done
echo "Scripts successfully symlinked!"

exit 0
