#!/bin/sh

setxkbmap us
# /usr/local/bin/dwmblocks &
# nm-applet &

while true; do
  dbus-run-session /bin/sh -c '
    /usr/local/bin/dwmblocks &
    nm-applet &
    exec /usr/local/bin/dwm
  ' 2> $HOME/.dwm.log
done
