import = ["~/.config/alacritty/themes/blood_moon.toml"]
live_config_reload = true
shell = { program = "/usr/bin/tmux", args = ["new-session", "-A", "-s", "general"] }

[env]
TERM = "xterm-256color"

[window]
padding = { x = 3, y = 3 }
opacity = 1.0
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }

[cursor]
style = { shape = "Beam", blinking = "Never" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "Y", mods = "Control", action = "ClearHistory" }
]
