[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[window]
padding = { x = 3, y = 3 }
opacity = 1.0
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = false

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
live_config_reload = true

[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session", "-A", "-s", "general"] }
