theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "always"
true-color = true
auto-save = true
mouse = false
# shell = ["zsh", "-c"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "register", "position", "file-encoding"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
backspace = { r = [":w", ":config-reload"], c = [":config-open"], l = [":buffer-close"], o = [":buffer-close-others"] }
C-z = ":earlier" # bind CTRL+Z to undo an earlier action
C-u = ":later" # bind CTRL+U to redo an action
C-d = ":w" # bind CTRL+D to save 

# Additional editor modifying bindings.
[keys.normal.space.e]
h = ":toggle lsp.display-inlay-hints"
